// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dhbzvxcqhrbfztiektwd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRoYnp2eGNxaHJiZnp0aWVrdHdkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg5NjA5NzYsImV4cCI6MjA3NDUzNjk3Nn0.Pb7wiov4CFTp1J-gNV_njz0jtwMY-orK4-JBv5m1mgM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});